### ISSUE TITLE
CSS Conflict with Structure 3.1.3

### ISSUE THREAD

**Issue by grantmx** [litzinger/Nerdery-Theme#4]
There is a pretty bad conflict with Structure (v 3.1.3) Tree View with this theme.  Its makes all the Parent and Children pages appear in a diagonal on the Tree View page (this would be the modules home page, if you will).  To fix this, I removed lines 357 through 381 in Override.css.  

This fixed the issue.  Thanks!

**Comment by litzinger** [comment]
Hi Grant. This was a known issue and fixed awhile back.
